//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopingcartWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productid { get; set; }
        public string productName { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public byte[] picture { get; set; }
    
        public virtual category category { get; set; }
    }
}
